In [1]:
import numpy as np

# Step 1: Create a random vector of size 15 with integers in the range 1 to 20
random_vector = np.random.randint(1, 21, size=15)
print("Random Vector:", random_vector)

# Step 2: Reshape the array to 3x5
reshaped_array = random_vector.reshape(3, 5)
print("\nReshaped Array (3x5):\n", reshaped_array)

# Step 3: Replace the max in each row by 0
# Iterate over each row and replace the maximum value with 0
for i in range(reshaped_array.shape[0]):
    max_value_index = np.argmax(reshaped_array[i])
    reshaped_array[i][max_value_index] = 0

print("\nArray after replacing max in each row by 0:\n", reshaped_array)

# Step 4: Create a 2D array of size 4x3 with 4-byte integers
two_d_array = np.zeros((4, 3), dtype=np.int32)
print("\n2D Array (4x3) with 4-byte integers:\n", two_d_array)
print("Shape of the 2D array:", two_d_array.shape)
print("Type of the array:", type(two_d_array))
print("Data type of the array elements:", two_d_array.dtype)


Random Vector: [15  3 19  4  6  4  9  1 14 11 10  8 13 10  4]

Reshaped Array (3x5):
 [[15  3 19  4  6]
 [ 4  9  1 14 11]
 [10  8 13 10  4]]

Array after replacing max in each row by 0:
 [[15  3  0  4  6]
 [ 4  9  1  0 11]
 [10  8  0 10  4]]

2D Array (4x3) with 4-byte integers:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
Shape of the 2D array: (4, 3)
Type of the array: <class 'numpy.ndarray'>
Data type of the array elements: int32


In [2]:
import numpy as np

# Define the matrix
A = np.array([[3, -2],
              [1,  0]])

# Compute the eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Display the results
print("Matrix A:")
print(A)
print("\nEigenvalues:")
print(eigenvalues)
print("\nRight Eigenvectors:")
print(eigenvectors)


Matrix A:
[[ 3 -2]
 [ 1  0]]

Eigenvalues:
[2. 1.]

Right Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [3]:
import numpy as np

# Define the array
array = np.array([[0, 1, 2],
                  [3, 4, 5]])

# Extract the diagonal elements
diagonal_elements = np.diag(array)

# Compute the sum of the diagonal elements
sum_of_diagonal = np.sum(diagonal_elements)

# Display the results
print("Array:")
print(array)
print("\nDiagonal Elements:", diagonal_elements)
print("Sum of Diagonal Elements:", sum_of_diagonal)


Array:
[[0 1 2]
 [3 4 5]]

Diagonal Elements: [0 4]
Sum of Diagonal Elements: 4


In [4]:
import numpy as np

# Define the original array
original_array = np.array([[1, 2],
                           [3, 4],
                           [5, 6]])

# Reshape to 2x3
reshaped_2x3 = original_array.reshape(2, 3)

# Reshape to 3x2 (original shape)
reshaped_3x2 = original_array.reshape(3, 2)

# Display the results
print("Original Array:")
print(original_array)
print("\nReshaped Array (2x3):")
print(reshaped_2x3)
print("\nReshaped Array (3x2):")
print(reshaped_3x2)


Original Array:
[[1 2]
 [3 4]
 [5 6]]

Reshaped Array (2x3):
[[1 2 3]
 [4 5 6]]

Reshaped Array (3x2):
[[1 2]
 [3 4]
 [5 6]]
